SAP/InfraBox

deploy/infrabox/templates/scheduler/deployment.yaml

The cluster name can be arbitrary.

Don't assume the cluster name

---

src/dashboard-client/src/App.vue

Preferably it should point to the current version of InfraBox installed.

Fix documentation link

---

src/job/infrabox_job/process.py

fix unicode error in console msg#issue67

---

deploy/infrabox/grafana/dashboards/cluster_inspector.json
deploy/infrabox/grafana/dashboards/global_dashboard.json

Little updates for the Cluster Inspector and the Global dashboard.
Details in commit 10f906e.

Dashboards Fixes

---

src/dashboard-client/src/models/Job.js

The UI should now precise to the user what is happening.
It should be tested to ensure it behave properly, but I still don't have any use case to test it for now.

Notification fix #78 

---

src/metrics/server.py

The Node inspector should now have a working job graph count

Fix missing metrics

---

src/api/handlers/projects/collaborators.py
src/api/handlers/projects/projects.py
src/openpolicyagent/policies/project.rego
src/openpolicyagent/policies/projects_collaborators.rego
src/openpolicyagent/policies/projects_projects.rego
src/openpolicyagent/policies/projects_secrets.rego
src/openpolicyagent/policies/projects_tokens.rego
src/openpolicyagent/policies/trigger.rego
src/openpolicyagent/policies/user.rego

Now the admin ist able to add collaborators and has all permissions the owner has. #157

Fix administrator permissions

---

src/openpolicyagent/policies/projects_build.rego

Fix build access for public projects

---

deploy/infrabox/templates/_helpers.tpl
deploy/infrabox/templates/function_crd.yaml
deploy/infrabox/templates/scheduler/deployment.yaml
src/api/handlers/projects/projects.py
src/db/migrations/00022.sql
src/github/trigger/trigger.py
src/job/entrypoint.sh
src/job/job.py
src/scheduler/kubernetes/scheduler.py

use ssh key to clone private github repos

---

src/api/handlers/job_api.py
src/api/handlers/project.py
src/api/handlers/projects/build.py
src/api/handlers/projects/jobs.py
src/dashboard-client/src/components/build/Gantt.vue
src/dashboard-client/src/components/job/JobDetail.vue
src/dashboard-client/src/components/utils/State.vue
src/dashboard-client/src/components/utils/StateBig.vue
src/dashboard-client/src/components/utils/StateCircleBig.vue
src/dashboard-client/src/main.js
src/dashboard-client/src/models/Build.js
src/dashboard-client/static/css/infrabox.css
src/db/migrations/00001.sql
src/github/review/review.py
src/job/job.py
src/pyinfrabox/infrabox/__init__.py
src/scheduler/kubernetes/scheduler.py

A job will be set to 'unstable' if the container finished with exit code == 0,
the the uploaded test result contains failed tests.
Fixes #139

Introduce new job state 'unstable'

---

src/openpolicyagent/policies/project.rego

This change resolve issue #181

Fix svg_images initialization

---

src/api/handlers/projects/projects.py
src/dashboard-client/src/components/project/ProjectDetailHeader.vue
src/dashboard-client/src/components/project/ProjectOverview.vue
src/dashboard-client/src/models/Project.js
src/dashboard-client/src/store.js

Show settings tab only for administrators and only the permitted action buttons

Userrole on frontend side

---

src/job/infrabox_job/process.py
src/job/job.py

adds a error token to the UI to guide the user to the questionable
section

print failure message when container exists

---

src/github/review/review.py

Quote project name in job URL reported to Github

---

src/gerrit/api/Dockerfile
src/gerrit/api/api.py
src/gerrit/review/Dockerfile
src/gerrit/trigger/Dockerfile
src/github/trigger/trigger.py
src/images/base/Dockerfile
src/images/test/Dockerfile

Replace bottle library scripts to flask library.
Need maybe some test (I don't know how do it on this script)

Migrate bottle to flask (need test)

---

deploy/infrabox/templates/_helpers.tpl
deploy/infrabox/templates/api/deployment.yaml
deploy/infrabox/templates/ingress.yaml
deploy/infrabox/templates/ingress_ha.yaml
deploy/infrabox/templates/saml/configmap.yaml
deploy/infrabox/values.yaml
docs/install/configure/saml.md
docs/install/install.md
infrabox/test/api/docker-compose.yml
infrabox/test/utils/saml-idp/docker-compose.yaml
src/api/handlers/account/__init__.py
src/api/handlers/account/advanced_settings.json
src/api/handlers/account/github.py
src/api/handlers/account/saml.py
src/api/handlers/account/settings.json
src/api/run_with_dummy.sh
src/api/settings.py
src/dashboard-client/src/App.vue
src/dashboard-client/src/components/Overview.vue
src/dashboard-client/src/components/account/Login.vue
src/dashboard-client/static/css/infrabox.css
src/openpolicyagent/policies/account_saml.rego

* Initial add of SAML account handler
* Add env variable INFRABOX_ACCOUNT_SAML_ENABLED
* Saml integration and test idp
* Registration and login with SAML
* Add SAML metadata endpoint
* Rego for SAML Metadata Endpoint
* Adding SSO to login page
* Add Legal and Privacy to frontend
* Read user data from SAML attributes
* SAML Advanced Settings
* SAML Single Logout (SLO)
* env variable for saml settings path
* Error handling for initiating single logouts
* Kubernetes configuration for saml and legal
* remove hardcoded legal
* Add slo to config
* Add new environment variables to unit test
* Remove Footer  when no leagal url was provided by the settings
* Add ingress config for /saml
* Change values and helpers for kubernetes config
* add saml and legal documentation
* fix typo in …

SAML SSO Support (#195)

---

src/dashboard-client/src/models/Job.js
src/dashboard-client/src/store.js

show date with user locale on dashboard

---

src/pyinfraboxutils/storage.py

Use flask ctx stack to judge if current session is inside a flask request.
This change fixes a error that happens when storage is called outside api server.

[storage]Minor refactor on storage

---

src/api/handlers/projects/jobs.py
src/dashboard-client/src/components/job/JobDetail.vue
src/dashboard-client/src/models/Job.js

Download all archives in one click

---

docs/job/docker.md

[documentation] container run command is ignored when build_only=true

---

src/github/trigger/trigger.py

Fix some issues with github triggers

---

src/openpolicyagent/policies/projects_projects.rego

Fix authorization for private projects

---

deploy/infrabox/templates/_helpers.tpl
deploy/infrabox/templates/checker/deployment.yaml
deploy/infrabox/templates/checker/service.yaml
deploy/infrabox/templates/checker/servicemonitor.yaml
src/checker/checker.py

+ Added summary metrics to storage upload/download
+ Added database SELECT 1 checking
+ Added total errors count metric

Integrated checker.py with Prometheus

---

src/services/gcp/pkg/stub/cleaner/k8sCleaner.go

The deletions ignored uninitialized resources so far. Further, this change now enforces the foregroundDeletion policy.

Delete uninitialized and wait for it until done

---

src/metrics/JSONserver.py
src/metrics/run.sh
src/metrics/server.py

Data can now be redirected by two webservers to decouple the database from Grafana

Changed Server.py and added JSONserver.py

---

run_k3s.sh

This should help getting started with InfraBox development on Macs.
Relevant for #378

Allow usage of run_k3s.sh on mac with Docker Desktop

---

src/dashboard-client/package-lock.json
src/dashboard-client/package.json

Revert "chore(dashboard): npm audit fix"

---

src/api/handlers/projects/jobs.py
src/dashboard-client/src/models/Job.js

fix bugs when job's name is like this:
Before:
a.1/a ==>a.2
Now:
a.1/a ==>a.1/a.1

Fix bug for restaring job

---

src/api/handlers/job_api.py
src/pyinfrabox/infrabox/__init__.py
src/scheduler/kubernetes/scheduler.py

1. use requests core max(0.3, limit/2) for job pod
2. always select the cluster which has more cpu/memory capacities.

Scheduler improvement

---

src/services/aks/Dockerfile

fix a bug caused by alpine 3.14

Fix: aks service test failed

---

src/collector-api/server.py
src/openpolicyagent/policies/project.rego
src/services/aks/Dockerfile
src/services/gcp/pkg/stub/handler.go

Add some logs to debug the error. Don't merge it now.

Fix gke logs
