SAP/InfraBox

src/grafana/Dockerfile, src/grafana/dashboards/build_inspector.json, src/grafana/dashboards/cluster_inspector.json, src/grafana/dashboards/dashboards.yaml, src/grafana/dashboards/global_dashboard.json, src/grafana/dashboards/job_inspector.json, src/grafana/dashboards/project_inspector.json, src/grafana/dashboards/projects_overview.json, src/grafana/datasources/datasources.yaml, src/pymetricserv/Dockerfile, src/pymetricserv/pyserv.py
First version of the Grafana server which should allow users to monitor the behaviors of clusters, projects, builds and jobs among Infrabox.
Implements a Grafana server and Python web server. 
The Grafana server displays datas from the Postgres Infrabox DB and the Prometheus DB. 
The Python repeatedly query datas from the Postgres DB to build metrics for the Prometheus DB.
=> Grafana visualization server

src/job/job.py
Cache is compressed with tar.snappy, but uncompressed with tar.gz, should be fixed.
=> fix cache syncing

src/api/handlers/projects/jobs.py
use bytesIO instead of request.raw object to support utf-8 encoded file.
=> fix download utf-8 encoded file

docs/job/git.md, src/job/job.py
When specifying commit as a commit sha, then this commit cannot be
fetched, therefore it has to be in the history, which is cloned.
=> git workflow allow to clone a specific branch other than master

src/api/handlers/job_api.py, src/api/handlers/project.py, src/api/handlers/projects/jobs.py, src/job/job.py, src/pyinfraboxutils/storage.py
1. Rework download archive
2. Add exists method for storage
3. Avoid duplicated uploads when use shared storage
=> Optimize storage performance

deploy/infrabox/templates/fluentbit/configmap.yaml, deploy/infrabox/templates/fluentbit/daemonset.yaml
Sometime fluentbit pod  is OOM killed. That's why we lost some logs
=> update fluentbit template

deploy/infrabox/templates/ingress.yaml, deploy/infrabox/values.yaml
This allows the annotation for autoconfiguring TLS with [Kube Lego](https://blog.jetstack.io/blog/kube-lego/) to be added.
I didn't update the docs because I'm not sure if it's better to add a new section or to replace the cert manager part with this method.
=> Add support for Kube-Lego for TLS with ingress

src/api/handlers/account/account.py, src/api/handlers/account/account_ldap.py, src/api/handlers/account/saml.py, src/db/migrations/00026.sql
It was possible to write an email with different lower/upper case
letters. All different combinations resulted in a different user being
created in the database. Always storing the email in lower case should
ensure that a unique email address maps also only to one user.
=> Store email address as lower case

src/services/gcp/pkg/apis/gcp/v1alpha1/types.go, src/services/gcp/pkg/stub/cleaner/k8sCleaner.go, src/services/gcp/pkg/stub/cleaner/k8sCleaner_test.go, src/services/gcp/pkg/stub/handler.go
- only consider cluster cleanup as done after 1 minute
- only delete pvc after all pods were removed
- always force-delete persistent volume claims
- only delete persistent volumes after all pvcs were deleted
=> Cluster cleanup

src/job/job.py
The `gcloud docker` commands are deprecated and give a warning:
```
15:16:28|gcloud auth activate-service-account --key-file /tmp/gcr_sa.json
15:16:29|Activated service account credentials for: [<snip>]
15:16:29|gcloud docker -a
15:16:29|WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.
15:16:29|
15:16:29|As an alternative, use `gcloud auth configure-docker` to configure `docker` to
15:16:29|use `gcloud` as a credential helper, then use `docker` as you would for non-GCR
15:16:29|registries, e.g. `docker pull gcr.io/project-id/my-image`. Add
15:16:29|`--verbosity=error` to silence this warning: `gcloud docker
15:16:29|--verbosity=error -- pull gcr.io/project-id/my-image`.
15:16:29|
15:16:29|See: …
```
=> Use new GCR authentication method

src/scheduler/kubernetes/scheduler.py
The api of newer k8s versions (tested with 1.14) doesn't accept namespaces
for namespace-less crds anymore.
=> Fix links for crds in k8s 1.14

infrabox/test/api/project_test.py, infrabox/test/api/test.py, infrabox/test/api/test_template.py, src/api/handlers/project.py, src/openpolicyagent/policies/project.rego
This endpoint allows fetching of the most recent version of an archived
file for a given job name. Getting the last version created from a
specific branch is available via the optional 'branch' parameter.
`/api/v1/projects/<project_id>/archive?filename=<filename>&job_name=<name>`
=> Add archive endpoint to project api

src/dashboard-client/src/components/job/JobDetail.vue, src/dashboard-client/src/models/Job.js
Previously the button was only enabled after the job completed, while
individual sections provided the same link as soon as more than 200
lines were written to that section.
fixes #384
=> Enable button to access the raw log as soon as any logs are available

deploy/infrabox/templates/checker/deployment.yaml, deploy/infrabox/templates/secrets/checker.yaml, deploy/infrabox/values.yaml, src/checker/checker.py, src/pyinfraboxutils/slack.py
To get notified when a cluster of a HA setup gets deactivated by
checker, a slack callback is added. As preparation for further changes
to the checker service the dev settings were enhanced and local source
directories are mounted into the pod.
=> Add slack hook to checker

src/job/job.py
some PR failed bacause the commit id in PR is too old.
for upload type job, we have `full_history` option in infrabox.json to enable full_history when clone repo.
for create_job_matrix job, we can't have this option, so just enable `full_history` by default.
=> add full_history for creating job.

docs/job/dependencies.md
Add explanation about files generated by a parent job also being available at build-time on the child job.
=> Extend job dependencies documentation

src/services/gardener/pkg/stub/shootOperations/delete.go
`confirmation.garden.sapcloud.io` is deprecated with https://github.com/gardener/gardener/pull/1833 and will be removed in a future release of gardener/gardener.
=> Do not use the deprecated confirmation annotation

docs/job/docker.md
Based on my latest interaction with @chengshifan, it appears that using specific `target`'s from a multi-stage Dockerfile was missing from the docs. Added it in this PR.
Best regards,
Andre.
=> Added documentation for using docker target

src/api/handlers/job_api.py
In recent usage of Vault integration via appRole, the error message was not clear enough to tell the developer the issue was an invalid `secret-id` that needed refreshing. This PR adds the full raw API response the the CI log in order to facilitate debugging.
Message was:
> Getting value from vault error: url is 'https://`<redacted>`/appRoleCredentials', validate way is appRole
It should become:
> Getting value from vault error: url is 'https://<redacted>/appRoleCredentials', validate way is appRole; API response: `<the raw response in text format>`
=> added API response on Vault access error

src/job/job.py
Make the contents of INFRABOX_CRONJOB  (true or false) available to the docker builds.
=> Add INFRABOX_CRONJOB to docker build args

README.md
This PR removes the dead build status link from the README.
fixes #534
=> remove build status link
